name: fstore
publish_to: "none"
description: Mobile commerce app by Flutter

# Release version: v3.8.0 (Do not change this line)
# A version number is three numbers separated by dots, like 1.2.43 - followed by an optional build number separated by a +.
# In Android, build-name is used as versionName while build-number used as versionCode.Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion. Read more about iOS versioning at https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3000

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  inspireui: 1.4.0

  flutterflow:
    path: apps/flutterflow/

  # Base
  intl: 0.17.0
  crypto: 3.0.2
  path_provider: 2.0.13
  url_launcher: 6.1.10
  flutter_secure_storage: 8.0.0
  hive: 2.2.3
  hive_flutter: 1.1.0
  http: 0.13.5
  http_auth: 1.0.1
  share: 2.0.4
  tuple: 2.0.1
  collection: 1.17.0
  quiver: 3.2.1
  async: 2.10.0
  html: 0.15.2
  vector_math: 2.1.4
  path: 1.8.2
  flutter_svg: 1.1.6 # depend on pay_android
  multiple_localization: 0.3.0


  # FIREBASE PACKAGES
  firebase_core: 2.7.1
  firebase_analytics: 10.1.5
  firebase_auth: 4.2.10
  firebase_remote_config: 3.0.14
  firebase_dynamic_links: 5.0.16
  cloud_firestore: 4.4.4

  # Additional Firebase packages. To prevent unexpected upgrade.
  firebase_core_platform_interface: 4.5.3
  firebase_analytics_platform_interface: 3.3.22
  firebase_auth_platform_interface: 6.11.12
  firebase_remote_config_platform_interface: 1.1.34
  firebase_dynamic_links_platform_interface: 0.2.3+31
  cloud_firestore_platform_interface: 5.11.4
  firebase_messaging_platform_interface: 4.2.15

  # PUSH NOTIFICATION
  firebase_messaging: 14.2.5
  notification_permissions: 0.6.1
  flutter_local_notifications: ^13.0.0
  onesignal_flutter: 3.5.0

  # STATE MANAGEMENT
  provider: 6.0.5
  get_it: 7.2.0

  # SPLASH SCREEN, ONBOARD
  lottie: 2.3.0
  rive: 0.10.3

  # WEB TOOLS
  html_unescape: 2.0.0
  webview_flutter: 4.0.6
  webview_flutter_web: 0.2.2+1
  responsive_builder: 0.6.4
  flutter_inappwebview: 5.7.2+3

  # HTML render
  flutter_widget_from_html_core: 0.9.1
  fwfh_svg: 0.7.2+1
  fwfh_cached_network_image: 0.7.0+4
  fwfh_url_launcher: 0.9.0+1
  fwfh_chewie: 0.7.1+1
  fwfh_webview: 0.7.0+1
  fwfh_text_style: 2.22.8+1

  # VIDEO
  youtube_player_iframe: ^4.0.4

  # MAP
  google_maps_flutter: 2.2.5
  geocode: 1.0.2
  location: 4.4.0

  # AUTHENTICATION
  local_auth: 2.1.6
  the_apple_sign_in: 1.1.1
  flutter_facebook_auth: 5.0.8
  google_sign_in: 6.0.2
  sms_autofill: 2.3.0

  # PERMISSION
  permission_handler: 10.2.0

  # FILES, IMAGES
  file_picker: 5.2.6
  cached_network_image: 3.2.3
  image: 4.0.15
  transparent_image: 2.0.1
  image_picker: 0.8.7
  flutter_native_image: 0.0.6+1
  flutter_cache_manager: 3.3.0
  wechat_assets_picker:  8.4.0   
  photo_manager: 2.5.2

  # TOOLS
  google_fonts: 4.0.3
  random_string: 2.3.1
  json_annotation: 4.8.0
  freezed_annotation: 2.2.0
  timeago: 3.3.0 # use intl 0.18.0
  universal_platform: 1.0.0+1
  uuid: 3.0.7
  easy_debounce: 2.0.3
  devicelocale: 0.6.0
  visibility_detector: 0.3.3
  rate_my_app: 1.1.4
  flutter_linkify: 5.0.2
  gms_check: 1.0.1
  new_version_plus: 0.0.3 # depend on razorpay_flutter
  video_player: 2.6.0
  google_mobile_ads: 2.3.0
  speech_to_text: 6.1.1

  # UI
  flutter_spinkit: 5.1.0
  smooth_page_indicator: 1.0.1
  animated_text_kit: 4.2.2
  flash: 2.0.5+1
  flutter_staggered_grid_view: 0.6.2
  pin_code_fields: 7.4.0
  country_pickers: 2.0.0
  dropdown_search: 5.0.6
  intro_slider: 4.2.0
  flutter_zoom_drawer: 3.0.4+1
  extended_image: 7.0.2
  dotted_decoration: 2.0.0
  awesome_card: 1.1.7
  qr_code_scanner: 1.0.1
  flutter_calendar_carousel: 2.4.1 # use intl 0.18.0
  sticky_headers: 0.3.0+2
  jumping_dot: ^0.0.4
  infinite_carousel: ^1.0.2
  charts_flutter_new: 0.12.0
  tiktoklikescroller: ^0.2.3
  readmore: ^2.2.0
  flutter_animate: 4.1.0

  ### Native Payment
  midtrans_sdk:
    git:
      url: https://github.com/inspireui/midtrans_sdk
      ref: 57ad626ed8621b70de485c2ba0798f2ab153bc4e
  razorpay_flutter: 1.3.4
  paytm_allinonesdk: 1.2.1
  flutter_paystack:
    git:
      url: https://github.com/inspireui/flutter_paystack
      ref: fdd0dc5b5d4591a6b508b97fe84270e10cc18875


  ### Flutter 3 fix warning
  flutter_swiper_null_safety:
    git: https://github.com/inspireui/flutter_swiper_null_safety
  flare_flutter:
    git:
      url: https://github.com/inspireui/Flare-Flutter.git
      ref: fd4bcba22aae4c028286e453deeb78f3311e689a
      path: flare_flutter
  pull_to_refresh:
    git: https://github.com/inspireui/flutter_pulltorefresh
  intl_phone_number_input:
    git: https://github.com/inspireui/intl_phone_number_input
  country_code_picker:
    git:
      url: https://github.com/inspireui/CountryCodePicker
      ref: 0d3978023a94415ab1339de445f15c737adec9b1
  flutterwave_standard:
    git:
      url: https://github.com/inspireui/Flutterwave
      ref: dd7da29b031fa5a9166b58ffc090eb0a69333b96


  ##---- Extended features ------ ###
  ## Native payment
  easy_paypal: 1.0.1
  pay: 1.1.0
  flutter_stripe: 7.0.0 # there is new breaking change in 8.0
  stripe_android: 7.0.1
  stripe_ios: 7.0.0
  stripe_platform_interface: 7.0.0
  stripe_sdk:
    git:
      url: https://github.com/inspireui/stripe-sdk
      ref: 005bf185f9b67bcfc9f853019f3e89c48a1026d6
  myfatoorah_flutter:
    git:
      url: https://github.com/inspireui/myfatoorah_flutter.git
      ref: c26ff9ba6b524f79ea160bb1d65d14fa86668e13
  in_app_purchase: 3.1.5


  ###---- Some extra feature is disable by default -----###
  ### ðŸ’³ Facebook Ads
  ### Search "Enable Facebook Ads" & uncomment to use  - https://tppr.me/9Pkf9
  # facebook_audience_network: 1.0.1

  ### â¬‡ï¸ Enable In App Update on Android feature
  ### Uncomment file lib/common/tools/in_app_update_for_android.dart
  #  in_app_update: 4.0.1

  ### CRM services
  ### ðŸ’¬ Zoho SalesIQ Mobilisten
  ### Search "Zoho SalesIQ Mobilisten" and uncomment to use - https://take.ms/McejF
  # salesiq_mobilisten: 2.0.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_native_splash: ^2.2.19
  build_runner: 2.3.3
  freezed: 2.3.2
  json_serializable: 6.6.0
  flutter_launcher_icons: "^0.13.1"

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  color: "#17202A"
  #background_image: "assets/background.png"

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  # image: "assets/images/3.png"

  # The branding property allows you to specify an image used as branding in the splash screen.
  # It must be a png file. It is supported for Android, iOS and the Web.  For Android 12,
  # see the Android 12 section below.
  branding: "assets/images/9.png"

  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  branding_mode: bottom

  # The color_dark, background_image_dark, image_dark, branding_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #branding_dark: assets/dart_dark.png

  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    color: "#17202A"
    branding: "assets/images/9.png"
    branding_mode: bottom

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  android: true
  ios: true
  #web: false


  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # The screen orientation can be set in Android with the android_screen_orientation parameter.
  # Valid parameters can be found here:
  # https://developer.android.com/guide/topics/manifest/activity-element#screen
  #android_screen_orientation: sensorLandscape

  # To hide the notification bar, use the fullscreen parameter.  Has no effect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: [SystemUiOverlay.bottom, SystemUiOverlay.top], );
  fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'

### Enable to use Flutter Test Driver
#  flutter_driver:
#    sdk: flutter
#  test: 1.16.5
#  dependency_validator: ^3.2.2  # pub run dependency_validator

### Enable Generate Icon library
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

#  Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/config/
    - lib/config/states/
    - lib/config/stories/
    - assets/icons/brands/
    - assets/icons/credit_cards/
    - assets/icons/tabs/
    - assets/icons/payment/
    - assets/icons/logins/
    - assets/images/
    - assets/images/country/
    - assets/images/favicon/
    - assets/map_styles/
    - assets/html/
    - google_fonts/

### Uncomment to use custom font
#  fonts:
#    - family: Your Custom Font
#      fonts:
#      - asset: google_fonts/GE-Hili-Book.ttf

flutter_intl:
  enabled: true
  use_deferred_loading: true
